controllers/ArticleController.php
<?php
/**
 * Created by PhpStorm.
 * User: mkornevich
 * Date: 10/22/2017
 * Time: 12:20 PM
 */

namespace app\controllers;

use app\components\project\ProjectFinder;
use app\models\base\Article;
use app\models\base\Project;
use app\models\frontend\FrontArticle;
use app\components\sort\ArticleSortManager;
use app\models\frontend\FrontProject;
use Yii;
use yii\data\Pagination;
use yii\filters\AccessControl;
use yii\helpers\Url;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

class ArticleController extends Controller
{
    public function behaviors()
    {
        return [
            [
                'class' => AccessControl::className(),
                'only' => ['edit', 'new', 'remove'],
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['edit', 'new', 'remove'],
                        'roles' => ['editAndAddArticle'],
                    ]
                ],

            ],
        ];
    }

    public function actionView($id)
    {
        $query = Article::find()->where(['id' => $id]);

        if (!Yii::$app->user->can('editAndAddArticle'))
            $query->andWhere('created_at < ' . time())
                ->andWhere('draft = 0');

        if (!$article = $query->one())
            throw new NotFoundHttpException('Статья не найдена');

        return $this->render('view', [
            'article' => $article,
            'canEditAndAddArticle' => Yii::$app->user->can('editAndAddArticle'),
        ]);
    }

    public function actionList()
    {

        $pagination = new Pagination();
        $articleSortManager = new ArticleSortManager(Yii::$app->request->get());

        $articlesQuery = $articleSortManager->getPrepareQuery(Article::find());

        if (!Yii::$app->user->can('editAndAddArticle'))
            $articlesQuery->andWhere('created_at < ' . time())
                ->andWhere('draft = 0');

        // для показа всех статей для проекта
        if ($projectId = Yii::$app->request->get('for-project')) {
            $articlesQuery->andWhere(['target_id' => (int)$projectId]);
            $articlesQuery->andWhere(['target_type' => Article::TARGET_TYPE_PROJECT]);
        }

        $pagination->totalCount = $articlesQuery->count();
        $pagination->defaultPageSize = 5;

        $articles = $articlesQuery
            ->limit($pagination->limit)
            ->offset($pagination->offset)
            ->all();

        return $this->render('list', [
            'pagination' => $pagination,
            'articles' => $articles,
            'columnSortViewData' => $articleSortManager->getPrepareViewData(),
            'canEditAndAddArticle' => Yii::$app->user->can('editAndAddArticle'),
        ]);
    }

    public function actionEdit($id)
    {
        $articleEditForm = FrontArticle::findOne($id);

        if (!$articleEditForm)
            throw new BadRequestHttpException('Такой статьи не существует.');

        $articleEditForm->scenario = FrontArticle::SCENARIO_EDIT_FORM;

        if (
            $articleEditForm->load(Yii::$app->request->post()) &&
            $articleEditForm->save()
        )
            return $this->redirect(Url::to(['article/view', 'id' => $articleEditForm->id]));

        return $this->render('edit', [
            'articleEditForm' => $articleEditForm,
            'articleRemoveForm' => new FrontArticle(['scenario' => FrontArticle::SCENARIO_REMOVE_FORM]),
        ]);
    }

    public function actionRemove()
    {
        $articleRemoveForm = new FrontArticle(['scenario' => FrontArticle::SCENARIO_REMOVE_FORM]);
        if (
            $articleRemoveForm->load(Yii::$app->request->post()) &&
            $articleRemoveForm->validate() &&
            $articleRemoveForm->deleteByThisId()
        )
            return $this->redirect(Url::to(['article/list']));
        else
            throw new BadRequestHttpException('Не удалось удалить статью.');
    }

    public function actionNew($id = '', $type = '', $mainProjectId = '')
    {
        $articleNewForm = new FrontArticle(['scenario' => FrontArticle::SCENARIO_NEW_FORM]);

        if (
            $articleNewForm->load(Yii::$app->request->post()) &&
            $articleNewForm->save()
        ){

            if(
                $mainProjectId != '' &&
                $project = Project::findOne($mainProjectId)
            ){
                $project->target_article = $articleNewForm->id;
                $project->save();
            }
            return $this->redirect(Url::to(['article/view', 'id' => $articleNewForm->id]));

        }

        $articleNewForm->target_type = $type;
        $articleNewForm->target_id = $id;

        return $this->render('new', [
            'articleNewForm' => $articleNewForm,
        ]);
    }
}

controllers/ProjectController.php
<?php

namespace app\controllers;


use app\components\category\CategoryFinder;
use app\components\project\ProjectFinder;
use app\components\projectListComponent\ProjectListAction;
use app\models\base\Article;
use app\models\base\Category;
use app\models\base\Project;
use app\models\frontend\FrontProject;
use Yii;
use yii\data\Pagination;
use yii\filters\AccessControl;
use yii\helpers\Url;
use yii\web\BadRequestHttpException;
use yii\web\Controller;

class ProjectController extends Controller
{

    public function behaviors()
    {
        return [
            [
                'class' => AccessControl::className(),
                'only' => ['edit', 'new', 'remove'],
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['edit', 'new', 'remove'],
                        'roles' => ['editAndAddProject'],
                    ]
                ],

            ],
        ];
    }

    public function actionList(){

        $categoryFinder = new CategoryFinder();
        $projectFinder = new ProjectFinder(Yii::$app->request->post('categories'));



        $phpProvider = [
            'startCategories' => $categoryFinder->getAllArrayCategories(),
            'startProjects' => $projectFinder->getStartProjects(),
            'canEditAndAddProject' => Yii::$app->user->can('editAndAddProject'),
        ];

        return $this->render('list', [
            'phpProvider' => json_encode($phpProvider, JSON_UNESCAPED_UNICODE)
        ]);
    }

    public function actionGetProjectsJson(){

        $projectFinder = new ProjectFinder(Yii::$app->request->post('categories'));

        $page = Yii::$app->request->post('page', 0);

        return json_encode($projectFinder->getProjectsByCategoryIds($page), JSON_UNESCAPED_UNICODE);
    }
    public function actionSearchProject($query){
        $projects = Project::find()
            ->select(['id', 'name'])
            ->orderBy(['rating' => SORT_DESC])
            ->where(['like', 'name', $query])
            ->limit(5)
            ->asArray()
            ->all();

        return json_encode($projects, JSON_UNESCAPED_UNICODE);
    }

    public function actionView($id)
    {
        $project = Project::findOne($id);

        if(!$project)
            throw new BadRequestHttpException('Проект не найден');

        Article::attachArticleTextAndDescriptionToProject($project);

        Category::attachCategoryDataToProject($project);

        return $this->render('view', [
            'project' => $project,
            'articleToThisProjectExist' => Article::find()
                ->where(['target_id' => $project->id])
                ->andWhere(['target_type' => Article::TARGET_TYPE_PROJECT])->exists(),
            'canEditAndAddProject' => Yii::$app->user->can('editAndAddProject'),
            'canEditAndAddArticle' => Yii::$app->user->can('editAndAddArticle'),
        ]);
    }

    public function actionEdit($id)
    {
        $projectEditForm = FrontProject::findOne($id);

        if (!$projectEditForm)
            throw new BadRequestHttpException('Проект не найден.');

        $projectEditForm->scenario = FrontProject::SCENARIO_EDIT_FORM;
        if (
            $projectEditForm->load(Yii::$app->request->post()) &&
            $projectEditForm->validate() &&
            $projectEditForm->save()
        ){
            $projectEditForm->updateSelectCategory();
            return $this->redirect(Url::to(['project/view', 'id' => $projectEditForm->id]));
        }


        return $this->render('edit', [
            'projectEditForm' => $projectEditForm,
            'projectRemoveForm' => new FrontProject(['scenario' => FrontProject::SCENARIO_REMOVE_FORM]),
            'projectId' => $id,
        ]);
    }

    public function actionRemove()
    {
        $projectRemoveForm = new FrontProject(['scenario' => FrontProject::SCENARIO_REMOVE_FORM]);

        if ($projectRemoveForm->load(Yii::$app->request->post()) &&
            $projectRemoveForm->validate() &&
            $projectRemoveForm->deleteByThisId()
        )
            return $this->redirect(Yii::$app->urlManager->createUrl('project/list'));
        else
            throw new BadRequestHttpException('Не удалось произвести удаление.');
    }

    public function actionNew()
    {
        $projectNewForm = new FrontProject(['scenario' => FrontProject::SCENARIO_NEW_FORM]);

        if ($projectNewForm->load(Yii::$app->request->post()) &&
            $projectNewForm->validate() &&
            $projectNewForm->save()
        ){
            $projectNewForm->updateSelectCategory();
            return $this->redirect(Yii::$app->urlManager->createUrl(['project/view', 'id' => $projectNewForm->id]));
        }

        return $this->render('new', [
            'projectNewForm' => $projectNewForm,
        ]);
    }
}

views/project/edit.php
<?php
/**
 * Created by PhpStorm.
 * User: mkornevich
 * Date: 10/11/2017
 * Time: 11:03 AM
 *
 * @var \app\models\frontend\FrontProject $projectEditForm
 * @var \app\models\frontend\FrontProject $projectRemoveForm
 * @var array $categories
 * @var integer $projectId
 */


use app\widgets\AttachedCategories\AttachedCategories;
use dosamigos\datepicker\DatePicker;
use vova07\imperavi\Widget;
use yii\bootstrap\ActiveForm;
use yii\helpers\Html;
use yii\helpers\Url;

$this->title = 'Редактирование проекта';

?>


<div class="content-panel">

    <div class="page-title">
        <span class="item app-color-blue app-header-font">Редактирование проекта <b><?= Html::encode($projectEditForm->name) ?></b></span>
    </div>

    <? $f = ActiveForm::begin() ?>

    <div class="row">

        <div class="col-md-6">

            <div class="row">
                <div class="col-sm-6">
                    <?= $f->field($projectEditForm, 'name')->textInput() ?>
                </div>
                <div class="col-sm-6">
                    <?= $f->field($projectEditForm, 'url')->textInput() ?>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-4">
                    <?= $f->field($projectEditForm, 'foundation_year')->input('number', ['max' => 9999, 'min' => 0]) ?>
                </div>
                <div class="col-sm-4">
                    <?= $f->field($projectEditForm, 'rating')->input('number') ?>
                </div>
                <div class="col-sm-4">
                    <?= $f->field($projectEditForm, 'target_article')->input('number') ?>
                    <? if( $projectEditForm->target_article ): ?>
                        <a class="btn btn-default pull-right" href="<?= Url::to(['article/edit', 'id' => $projectEditForm->target_article]) ?>">Редактировать статью</a>
                    <? else: ?>




                        <? if ($projectEditForm->target_article > 0): ?>
                            <a target="_blank" class="btn btn-default pull-right" href="<?= Url::to(['article/edit', 'id' => $projectEditForm->target_article]) ?>">Редактировать гл. статью</a>
                        <? else: ?>
                            <a target="_blank" class="btn btn-default pull-right" href="<?= Url::to(['article/new', 'mainProjectId' => $projectEditForm->id]) ?>">Добавить гл. статью</a>
                        <? endif; ?>


                    <? endif; ?>
                </div>
            </div>

            <div style="margin-top: 10px" class="fix-overflow">
                <div class="btn-group pull-right">

                    <?= Html::submitButton('Применить изменения', ['class' => 'btn btn-primary', 'formaction' => Url::to(['project/edit', 'id' => $projectId])]) ?>

                    <?= Html::submitButton('Удалить', ['class' => 'btn btn-danger', 'formaction' => Url::to(['project/remove'])]) ?>


                </div>
            </div>
            <?= $f->field($projectRemoveForm, 'id')->hiddenInput(['value' => $projectId])->label(false) ?>


        </div>

        <div class="col-md-6">
            <?= $f->field($projectEditForm, 'selectCategory')->widget(AttachedCategories::className()) ?>
        </div>



    </div>





    <? ActiveForm::end() ?>


</div>

views/project/list.php
<?php
/**
 * Created by PhpStorm.
 * User: mkornevich
 * Date: 11/9/2017
 * Time: 9:50 PM
 *
 * @var yii/web/View $this
 * @var array $jsonCategories
 */


use app\assets\ProjectListAsset;
use app\assets\VueAsset;
use app\components\category\CategoryFinder;
use yii\helpers\Url;

VueAsset::register($this);
ProjectListAsset::register($this);

$this->title = 'Проекты';

?>


<div class="site-list" id="project-list-viewer" hidden>

    <div v-if="alertLoadedBlockShow" class="alert alert-success">
        Подождите пожалуйста мы загружаем данные!
    </div>


    <div class="item" v-for="project in projects">

        <div class="col-one">
            <div class="p-panel">
                <div class="p-panel-header red"><i class="glyphicon glyphicon-folder-close"></i>
                    {{ project.name }}
                </div>
                <div class="p-panel-body">
                    <p v-html="project.description || 'К этому проекту краткое описание не задано.' "></p>
                </div>
            </div>

            <div class="p-panel">
                <div class="p-panel-header grey"><i class="glyphicon glyphicon-tags"></i>Категории</div>
                <div class="p-panel-body">
                    <div class="category-viewer">
                        <div class="category-group" v-for="item in parseCategory(project.categoryIds)">
                            <span class="category-group-name">{{ item.rootName }} </span>
                            <span class="category-item" v-for="childName in item.names">{{ childName }}</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-two">
            <div class="p-panel">
                <div class="p-panel-header green"><i class="glyphicon glyphicon-info-sign"></i>Информация
                </div>
                <div class="p-panel-body">
                    <div class="info-viewer">
                        <div class="info-group">
                            <i class="glyphicon glyphicon-star red"></i>
                            <span class="info-name">Рейтинг</span>
                            <span class="info-value">{{ project.rating }}</span>
                        </div>
                        <div class="info-group">
                            <i class="glyphicon glyphicon-time green"></i>
                            <span class="info-name">Год основания</span>
                            <span class="info-value">{{ (project.foundation_year == 0) ? 'не указано' : project.foundation_year}}</span>
                        </div>
                    </div>
                </div>
            </div>

            <div class="p-panel">
                <div class="p-panel-header grey"><i class="glyphicon glyphicon-th-list"></i>Действия</div>
                <div class="p-panel-body">
                    <div class="actions">
                        <ul>
                            <li v-if="canEditAndAddProject">
                                <a target="_blank"
                                   :href="project.url_to_edit"
                                   class="button view">
                                    Редактировать
                                </a>
                            <li>
                                <a target="_blank"
                                   :href="project.url_to_view"
                                   class="button view">
                                    Читать подробнее
                                </a>
                            <li>
                                <a target="_blank"
                                   :href="project.url_to_project"
                                   class="button show-site">
                                    Открыть сайт
                                </a>

                        </ul>
                    </div>
                </div>
            </div>


        </div>

    </div>


    <div v-if="projects.length < 1" class="alert alert-danger">
        Ничего не найдено!
    </div>

    <button v-else @click="loadNext" id="load-next-button" class="btn btn-primary">Загрузить еще</button>

</div>


<? $this->beginBlock('leftColumn') ?>

<div class="site-column-style" hidden>
    <div class="title">Панель поиска</div>

    <div class="sub-title">Поиск по названию</div>

    <div id="search" class="content">
        <div class="search-element">
            <input @keyup="loadSearchData" placeholder="Начинайте вводить" v-model="searchQuery" class="search-input" type="text">
            <i @click="searchQuery = ''" v-if="searchQuery != ''" class="remove glyphicon glyphicon-remove red"></i>
        </div>

        <div v-if="searchQuery !== ''" class="search-result">
            <div v-for="item in searchResult" @click="goToProject(item.id)" class="search-item">{{item.name}}</div>
        </div>

    </div>

    <div class="sub-title">Поиск по категориям</div>

    <div id="category-tree" class="content-no-padding">
        <div v-if="parentCategory.parentId === 0" v-for="parentCategory in categoryData">
            <div @click="parentCategory.expand = !parentCategory.expand" class="parent-category">
                <i :class="'glyphicon glyphicon-triangle-' + (parentCategory.expand ? 'top': 'bottom') + ' orange'"></i> {{ parentCategory.name }}
            </div>
            <div v-if="parentCategory.expand" class="children-list">
                <div @click="toggleCheckBox(childrenCategory)" class="children-category" v-for="childrenCategory in getChildren(parentCategory)">
                    <span :style="childrenCategory.select ? 'color: black;' : 'color: grey;'">{{childrenCategory.name}}</span>
                </div>
            </div>

        </div>

    </div>


</div>


<? $this->endBlock() ?>


<script type="text/javascript">

    phpProvider = JSON.parse('<?= $phpProvider ?>');

</script>

views/project/new.php
<?php
/**
 * Created by PhpStorm.
 * User: mkornevich
 * Date: 10/11/2017
 * Time: 11:03 AM
 *
 * @var \app\models\frontend\FrontProject $projectNewForm
 * @var array $categories
 */

use app\widgets\AttachedCategories\AttachedCategories;
use dosamigos\datepicker\DatePicker;
use vova07\imperavi\Widget;
use yii\bootstrap\ActiveForm;
use yii\helpers\Html;
use yii\helpers\Url;

$this->title = 'Добавление проекта';

?>

<div class="content-panel">

    <div class="page-title">
        <span class="item app-color-blue app-header-font">Добавление нового проекта</span>
    </div>

    <? $f = ActiveForm::begin() ?>

    <div class="row">

        <div class="col-md-6">

            <div class="row">
                <div class="col-sm-6">
                    <?= $f->field($projectNewForm, 'name')->textInput() ?>
                </div>
                <div class="col-sm-6">
                    <?= $f->field($projectNewForm, 'url')->textInput() ?>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-4">
                    <?= $f->field($projectNewForm, 'foundation_year')->input('number', ['max' => 9999, 'min' => 0]) ?>
                </div>
                <div class="col-sm-4">
                    <?= $f->field($projectNewForm, 'rating')->input('number') ?>
                </div>
                <div class="col-sm-4">
                    <?= $f->field($projectNewForm, 'target_article')->input('number') ?>
                </div>
            </div>

            <div style="margin-top: 10px" class="fix-overflow">
                <div class="btn-group pull-right">

                    <?= Html::submitButton('Добавить проект', ['class' => 'btn btn-primary']) ?>

                </div>
            </div>


        </div>

        <div class="col-md-6">
            <?= $f->field($projectNewForm, 'selectCategory')->widget(AttachedCategories::className()) ?>
        </div>



    </div>

    <? ActiveForm::end() ?>

</div>

views/project/view.php
<?php
/**
 * Created by PhpStorm.
 * User: mkornevich
 * Date: 10/7/2017
 * Time: 9:47 PM
 *
 * @var \app\models\base\Project $project
 * @var array $categories
 * @var view $this ;
 *
 * @var bool $canEditAndAddArticle ;
 * @var bool $canEditAndAddProject ;
 * @var bool $articleToThisProjectExist
 */

use app\models\frontend\FrontArticle;
use app\widgets\SuggestedArticles\SuggestedArticles;
use yii\bootstrap\ActiveForm;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\web\View;

$this->title = 'Проект - ' . Html::encode($project->name);

?>


<div class="content-panel">


    <div class="page-title">
        <span class="font-size-2 blue">Проект <b><?= Html::encode($project->name) ?></b></span>
    </div>


    <div class="fix-overflow">
        <p><?= $project->text ?? 'Сейчас здесь нет текста загляните позже' ?></p>
    </div>


    <!-- comments -->
    <div id="disqus_thread"></div>
    <script>

        var disqus_config = function () {
            this.page.url = '<?= Url::to(['project/view', 'id' => $project->id], true) ?>';  // Replace PAGE_URL with your page's canonical URL variable
            this.page.identifier = '<?= 'project_' . $project->id ?>'; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
        };

        (function () { // DON'T EDIT BELOW THIS LINE
            var d = document, s = d.createElement('script');
            s.src = 'https://money-catalog.disqus.com/embed.js';
            s.setAttribute('data-timestamp', +new Date());
            (d.head || d.body).appendChild(s);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by
            Disqus.</a></noscript>

</div>












<? $this->beginBlock('leftColumn'); ?>

<div class="site-column-style">
    <? if ($canEditAndAddArticle or $canEditAndAddProject or $articleToThisProjectExist): ?>
        <div class="title">Действия</div>
    <? endif; ?>

    <div class="content-no-padding">

        <? if ($canEditAndAddProject): ?>
            <a class="styled-item" href="<?= Url::to(['project/edit', 'id' => $project->id]) ?>">
                <i class="glyphicon glyphicon-pencil"></i>
                <span class="orange">Редактировать проект</span>
            </a>
        <? endif; ?>

        <? if ($canEditAndAddArticle): ?>

            <? if ($project->target_article > 0): ?>
                <a class="styled-item"
                   href="<?= Url::to(['article/edit', 'id' => $project->target_article]) ?>">
                    <i class="glyphicon glyphicon-pencil"></i>
                    <span class="green">Редактировать гл. статью</span>
                </a>
            <? else: ?>
                <a class="styled-item"
                   href="<?= Url::to(['article/new', 'mainProjectId' => $project->id]) ?>">
                    <i class="glyphicon glyphicon-plus"></i>
                    <span class="green">Создать гл. статью</span>
                </a>
            <? endif; ?>

            <a class="styled-item"
               href="<?= Url::to(['article/new', 'id' => $project->id, 'type' => FrontArticle::TARGET_TYPE_PROJECT]) ?>">
                <i class="glyphicon glyphicon-list-alt"></i>
                <span class="green">Добавить статью</span>
            </a>
        <? endif; ?>

        <? if ($articleToThisProjectExist): ?>
            <a class="styled-item" href="<?= Url::to(['article/list', 'for-project' => $project->id]) ?>">
                <i class="glyphicon glyphicon-list-alt"></i>
                <span class="blue">См. статьи про этот проект</span>
            </a>
        <? endif; ?>

    </div>
    <div class="title">Информация</div>
    <div class="content-no-padding key-value-styled-info">
        <div class="info-group">
            <i class="glyphicon glyphicon-time blue"></i>
            <span class="info-name">Дата основания</span>

            <? if ($project->foundation_year): ?>
                <span class="info-value"><?= $project->foundation_year ?> г.</span>
            <? else: ?>
                <span class="info-value red">не указана</span>
            <? endif; ?>


        </div>
        <div class="info-group">
            <i class="glyphicon glyphicon-star red"></i>
            <span class="info-name">Рейтинг</span>
            <span class="info-value"><?= Html::encode($project->rating) ?></span>
        </div>
    </div>
    <div class="sub-title">Категории</div>
    <div class="content-no-padding" id="project-view-category-viewer">

        <? foreach ($project->categoryData as $categoryGroup): ?>
            <div class="category-group">
                <div class="category-title"><?= $categoryGroup['rootName'] ?></div>
                <? foreach ($categoryGroup['names'] as $name): ?>
                    <div class="category-item"><?= $name ?></div>
                <? endforeach; ?>
            </div>
        <? endforeach; ?>

    </div>

    <?= SuggestedArticles::widget(['data' => $project]) ?>

</div>

<? $this->endBlock(); ?>