controllers/ArticleController.php
<?php
/**
 * Created by PhpStorm.
 * User: mkornevich
 * Date: 10/22/2017
 * Time: 12:20 PM
 */

namespace app\controllers;

use app\components\project\ProjectFinder;
use app\models\base\Article;
use app\models\base\Project;
use app\models\frontend\FrontArticle;
use app\components\sort\ArticleSortManager;
use app\models\frontend\FrontProject;
use Yii;
use yii\data\Pagination;
use yii\filters\AccessControl;
use yii\helpers\Url;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

class ArticleController extends Controller
{
    public function behaviors()
    {
        return [
            [
                'class' => AccessControl::className(),
                'only' => ['edit', 'new', 'remove'],
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['edit', 'new', 'remove'],
                        'roles' => ['editAndAddArticle'],
                    ]
                ],

            ],
        ];
    }

    public function actionView($id)
    {
        $query = Article::find()->where(['id' => $id]);

        if (!Yii::$app->user->can('editAndAddArticle'))
            $query->andWhere('created_at < ' . time())
                ->andWhere('draft = 0');

        if (!$article = $query->one())
            throw new NotFoundHttpException('Статья не найдена');

        return $this->render('view', [
            'article' => $article,
            'canEditAndAddArticle' => Yii::$app->user->can('editAndAddArticle'),
        ]);
    }

    public function actionList()
    {

        $pagination = new Pagination();
        $articleSortManager = new ArticleSortManager(Yii::$app->request->get());

        $articlesQuery = $articleSortManager->getPrepareQuery(Article::find());

        if (!Yii::$app->user->can('editAndAddArticle'))
            $articlesQuery->andWhere('created_at < ' . time())
                ->andWhere('draft = 0');

        // для показа всех статей для проекта
        if ($projectId = Yii::$app->request->get('for-project')) {
            $articlesQuery->andWhere(['target_id' => (int)$projectId]);
            $articlesQuery->andWhere(['target_type' => Article::TARGET_TYPE_PROJECT]);
        }

        $pagination->totalCount = $articlesQuery->count();
        $pagination->defaultPageSize = 5;

        $articles = $articlesQuery
            ->limit($pagination->limit)
            ->offset($pagination->offset)
            ->all();

        return $this->render('list', [
            'pagination' => $pagination,
            'articles' => $articles,
            'columnSortViewData' => $articleSortManager->getPrepareViewData(),
            'canEditAndAddArticle' => Yii::$app->user->can('editAndAddArticle'),
        ]);
    }

    public function actionEdit($id)
    {
        $articleEditForm = FrontArticle::findOne($id);

        if (!$articleEditForm)
            throw new BadRequestHttpException('Такой статьи не существует.');

        $articleEditForm->scenario = FrontArticle::SCENARIO_EDIT_FORM;

        if (
            $articleEditForm->load(Yii::$app->request->post()) &&
            $articleEditForm->save()
        )
            return $this->redirect(Url::to(['article/view', 'id' => $articleEditForm->id]));

        return $this->render('edit', [
            'articleEditForm' => $articleEditForm,
            'articleRemoveForm' => new FrontArticle(['scenario' => FrontArticle::SCENARIO_REMOVE_FORM]),
        ]);
    }

    public function actionRemove()
    {
        $articleRemoveForm = new FrontArticle(['scenario' => FrontArticle::SCENARIO_REMOVE_FORM]);
        if (
            $articleRemoveForm->load(Yii::$app->request->post()) &&
            $articleRemoveForm->validate() &&
            $articleRemoveForm->deleteByThisId()
        )
            return $this->redirect(Url::to(['article/list']));
        else
            throw new BadRequestHttpException('Не удалось удалить статью.');
    }

    public function actionNew($id = '', $type = '', $mainProjectId = '')
    {
        $articleNewForm = new FrontArticle(['scenario' => FrontArticle::SCENARIO_NEW_FORM]);

        if (
            $articleNewForm->load(Yii::$app->request->post()) &&
            $articleNewForm->save()
        ){

            if(
                $mainProjectId != '' &&
                $project = Project::findOne($mainProjectId)
            ){
                $project->target_article = $articleNewForm->id;
                $project->save();
            }
            return $this->redirect(Url::to(['article/view', 'id' => $articleNewForm->id]));

        }

        $articleNewForm->target_type = $type;
        $articleNewForm->target_id = $id;

        return $this->render('new', [
            'articleNewForm' => $articleNewForm,
        ]);
    }
}

views/article/edit.php
<?php
/**
 * Created by PhpStorm.
 * User: mkornevich
 * Date: 10/22/2017
 * Time: 12:29 PM
 *
 * @var \app\models\frontend\FrontArticle $articleEditForm ;
 * @var \app\models\frontend\FrontArticle $articleRemoveForm ;
 */
use app\models\frontend\FrontArticle;
use dosamigos\datepicker\DatePicker;
use vova07\imperavi\Widget;
use yii\bootstrap\ActiveForm;
use yii\helpers\Html;
use yii\helpers\Url;

$this->title = 'Редактирование статьи';

?>

<div class="content-panel">

    <div class="page-title">
        <span class="item app-color-blue app-header-font">Редактирование статьи <b><?= Html::encode($articleEditForm->name) ?></b></span>
    </div>

    <? $f = ActiveForm::begin() ?>

    <div class="row">
        <div class="col-sm-3">
            <?= $f->field($articleEditForm, 'name') ?>
        </div>
        <div class="col-sm-3">
            <?= $f->field($articleEditForm, 'formattedCreatedAt')->widget(DatePicker::className(), [
                // modify template for custom rendering
                'language' => 'ru',
                'clientOptions' => [
                    'format' => 'dd.mm.yyyy',
                ]
            ]) ?>
        </div>
        <div class="col-sm-3">
            <?= $f->field($articleEditForm, 'target_id') ?>
        </div>
        <div class="col-sm-3">
            <?= $f->field($articleEditForm, 'target_type')->dropDownList([
                FrontArticle::TARGET_TYPE_CATEGORY => 'Категория',
                FrontArticle::TARGET_TYPE_PROJECT => 'Проект',
            ]) ?>
        </div>
    </div>

    <?= $f->field($articleEditForm, 'description')->textarea() ?>
    <div class="fix-overflow">
        <div class="text-align-right">
            <div class="btn-group">
                <?= Html::submitButton('Изменить', ['class' => 'btn btn-primary', 'formaction' => Url::to(['article/edit', 'id' => $articleEditForm->id])]) ?>
                <?= Html::submitButton('Удалить', ['class' => 'btn btn-danger', 'formaction' => Url::to(['article/remove'])]) ?>
            </div>
            <?= $f->field($articleEditForm, 'draft')->checkbox() ?>
        </div>
    </div>
    <?= $f->field($articleEditForm, 'text')->widget(Widget::className(), [
        'settings' => [
            'lang' => 'ru',
            'minHeight' => 200,
            'plugins' => Yii::$app->params['imperaviEditorPlugins'],
            'imageManagerJson' => Url::toRoute(['site/images-get']),
            'imageUpload' => Url::toRoute(['site/image-upload']),
        ]
    ]) ?>

    <?= $f->field($articleRemoveForm, 'id')->hiddenInput(['value' => $articleEditForm->id])->label(false) ?>

    <? ActiveForm::end() ?>

</div>

views/article/list.php
<?php
/**
 * @var app\models\base\Article[] $articles
 *
 * @var \yii\data\Pagination $pagination
 *
 * @var \yii\web\View $this
 *
 * @var bool $canEditAndAddArticle
 * @var string[] $targetNames
 *
 * @var array $columnSortViewData
 */

use yii\helpers\Html;
use yii\helpers\Url;

$this->title = 'Статьи';

?>


<div id="site-list" class="site-list">


    <? $if = 0;
    foreach ($articles as $article): ?>
        <div class="item">

            <div class="col-one">
                <div class="p-panel">
                    <div class="p-panel-header red"><i class="glyphicon glyphicon-list-alt"></i>
                        <?= Html::encode($article->name) ?>
                    </div>
                    <div class="p-panel-body">
                        <p>
                            <?= Html::encode($article->description) ?>
                        </p>
                    </div>
                </div>
            </div>

            <div class="col-two">
                <div class="p-panel">
                    <div class="p-panel-header green"><i class="glyphicon glyphicon-info-sign"></i>Информация
                    </div>
                    <div class="p-panel-body">
                        <div class="info-viewer">
                            <div class="info-group">
                                <i class="glyphicon glyphicon-time green"></i>
                                <? if ($article->created_at): ?>

                                    <span class="info-name">Опубликована</span>
                                    <span class="info-value">
                                        <?= Yii::$app->formatter->asDate($article->created_at, 'php:d.m.yy') ?>
                                    </span>

                                <? endif; ?>


                            </div>

                            <? if ($article->draft): ?>
                                <div class="info-group">
                                    <i class="glyphicon glyphicon-pencil red"></i>
                                    <span class="info-name">Черновик</span>
                                </div>
                            <? endif; ?>

                        </div>
                    </div>
                </div>

                <div class="p-panel">
                    <div class="p-panel-header grey"><i class="glyphicon glyphicon-th-list"></i>Действия</div>
                    <div class="p-panel-body">
                        <div class="actions">
                            <ul>

                                <? if ($canEditAndAddArticle): ?>
                                <li>
                                    <a href="<?= Url::to(['article/edit', 'id' => $article->id]) ?>"
                                       class="button view">
                                        Редактировать
                                    </a>
                                    <? endif; ?>


                                <li>
                                    <a href="<?= Url::to(['article/view', 'id' => $article->id]) ?>"
                                       class="button view">
                                        Читать полностью
                                    </a>


                            </ul>
                        </div>
                    </div>
                </div>


            </div>

        </div>


        <? $if = 1;
    endforeach;
    if ($if): ?>

        <?= \yii\widgets\LinkPager::widget(['pagination' => $pagination]) ?>

    <? else: ?>
        <div class="alert alert-danger">Ничего не найдено</div>
    <? endif; ?>
</div>

<? $this->beginBlock('leftColumn') ?>
<div class="site-column-style">

    <div class="title">Сортировка</div>


    <? foreach ($columnSortViewData as $sortGroup): ?>

    <div class="sub-title"><?= $sortGroup['text'] ?></div>

    <div class="content-no-padding">
        <? foreach ($sortGroup['items'] as $sortGroupItem): ?>


    <? if ($sortGroupItem['goUrl']): ?>
        <div onclick="location.href = '<?= $sortGroupItem['goUrl'] ?>'" class="styled-item">

            <? else: ?>
            <div class="styled-item">
                <? endif; ?>


                <span class="name <?= ($sortGroupItem['isActive']) ? 'red' : '' ?>"><?= $sortGroupItem['text'] ?></span>

            </div>
            <? endforeach; ?>
        </div>
        <? endforeach; ?>


    </div>
    <? $this->endBlock(); ?>

views/article/new.php
<?php
/**
 * Created by PhpStorm.
 * User: mkornevich
 * Date: 10/22/2017
 * Time: 12:29 PM
 *
 * @var \app\models\frontend\FrontArticle $articleNewForm;
 */
use app\models\frontend\FrontArticle;
use dosamigos\datepicker\DatePicker;
use vova07\imperavi\Widget;
use yii\bootstrap\ActiveForm;
use yii\helpers\Html;
use yii\helpers\Url;

$this->title = 'Добавление статьи';

?>

<div class="content-panel">

    <div class="page-title">
        <span class="item app-color-blue app-header-font">Добавление новой статьи</span>
    </div>
    <? $f = ActiveForm::begin() ?>

    <div class="row">
        <div class="col-sm-3">
            <?= $f->field($articleNewForm, 'name') ?>
        </div>

        <div class="col-sm-3">
            <?= $f->field($articleNewForm, 'formattedCreatedAt')->widget(DatePicker::className(), [
                'language' => 'ru',
                'clientOptions' => [
                    'format' => 'dd.mm.yyyy',
                ]
            ]) ?>
        </div>

        <div class="col-sm-3">
            <?= $f->field($articleNewForm, 'target_id') ?>
        </div>
        <div class="col-sm-3">
            <?= $f->field($articleNewForm, 'target_type')->dropDownList([
                FrontArticle::TARGET_TYPE_CATEGORY => 'Категория',
                FrontArticle::TARGET_TYPE_PROJECT => 'Проект',
            ]) ?>
        </div>
    </div>

    <?= $f->field($articleNewForm, 'description')->textarea() ?>
    <div class="fix-overflow">
        <div class="pull-right text-align-right">
            <div class="btn-group">
                <?= Html::submitButton('Добавить', ['class' => 'btn btn-primary']) ?>
            </div>
            <?= $f->field($articleNewForm, 'draft')->checkbox() ?>
        </div>
    </div>
    <?= $f->field($articleNewForm, 'text')->widget(Widget::className(), [
        'settings' => [
            'lang' => 'ru',
            'minHeight' => 200,
            'plugins' => Yii::$app->params['imperaviEditorPlugins'],
            'imageManagerJson' => Url::toRoute(['site/images-get']),
            'imageUpload' => Url::toRoute(['site/image-upload']),
        ]
    ]) ?>

    <? ActiveForm::end() ?>

</div>

views/article/view.php
<?php
/**
 * Created by PhpStorm.
 * User: mkornevich
 * Date: 10/22/2017
 * Time: 12:28 PM
 *
 * @var \app\models\base\Article $article ;
 * @var bool $canEditAndAddArticle
 */
use app\widgets\SuggestedArticles\SuggestedArticles;
use yii\helpers\Html;
use yii\helpers\Url;

$this->title = 'Статья - ' . Html::encode($article->name);

?>

<div class="content-panel">


    <div class="page-title">
        <span class="font-size-2 blue">Статья <b><?= Html::encode($article->name) ?></b></span>
    </div>


    <div style="overflow: hidden">
        <p><?= $article->text ?></p>
    </div>

<!-- comments -->
    <div id="disqus_thread"></div>
    <script>

        var disqus_config = function () {
            this.page.url = '<?= Url::to(['article/view', 'id' => $article->id], true) ?>';  // Replace PAGE_URL with your page's canonical URL variable
            this.page.identifier = '<?= 'article_' . $article->id ?>'; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
        };

        (function() { // DON'T EDIT BELOW THIS LINE
            var d = document, s = d.createElement('script');
            s.src = 'https://money-catalog.disqus.com/embed.js';
            s.setAttribute('data-timestamp', +new Date());
            (d.head || d.body).appendChild(s);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>


</div>



<? $this->beginBlock('leftColumn'); ?>

<div class="site-column-style">
    <? if($canEditAndAddArticle): ?>
        <div class="title">Действия</div>
    <? endif; ?>

    <div class="content-no-padding">

        <? if ($canEditAndAddArticle): ?>
            <a class="styled-item" href="<?= Url::to(['article/edit', 'id' => $article->id]) ?>">
                <i class="glyphicon glyphicon-pencil"></i>
                <span class="orange">Редактировать</span>
            </a>
        <? endif; ?>

    </div>
    <div class="title">Информация</div>
    <div style="padding-bottom: 3px" class="content-no-padding key-value-styled-info">

        <? if($article->draft): ?>
            <div class="info-group">
                <i class="glyphicon glyphicon-pencil"></i>
                <span class="info-name">Это черновик</span>
            </div>
        <? endif; ?>

        <div class="info-group">
            <i class="glyphicon glyphicon-time orange"></i>

            <? if($article->created_at and $article->updated_at): ?>
                <? $articleTime = Html::encode(Yii::$app->formatter->asDate($article->created_at, 'php:d.m.yy')) ?>

                <? if ($article->created_at + 86400 > $article->updated_at): ?>
                    <span class="info-name">Cтатья создана</span>
                    <span class="info-value"><?= $articleTime ?></span>
                <? else: ?>
                    <span class="info-name">Cтатья обновлена</span>
                    <span class="info-value"><?= $articleTime ?></span>
                <? endif; ?>
            <? endif; ?>

        </div>

    </div>

    <?= SuggestedArticles::widget(['data' => $article]) ?>

</div>

<? $this->endBlock('leftColumn'); ?>